### ISSUE TITLE
[Question] What is the [callback, url] field used for?

### ISSUE THREAD

**Issue by erreip** [miller-hacks/huigma#2]
What is the [callback, url] field used for? Is there specific imput for that field?

![image](https://cloud.githubusercontent.com/assets/9080659/6393864/90efb92c-bd9b-11e4-8924-419c9d359b6c.png)

**Comment by AyumuKasuga** [comment]
This feature is not working yet, sorry. This url will be hit when someone open your url. You can send us pull request with your implementation :)

**Comment by erreip** [comment]
Got it. Thanks!
